name: UtilityPlugin
version: '${project.version}'
main: org.dbwztools.es.utilityplugin.UtilityPlugin
api-version: '1.21'
authors:
  - DelawareX
  - Nukedev
commands:
  suicide:
    description: Utilizalo para suicidarte
    usage: /suicide
  falsificar:
    description: Utilizalo para falsificar un mensaje de un Jugador
    usage: /falsificar <player> <message>
  prohibir:
    description: Utilizalo para prohibir un Item
    usage: /prohibir
  invisible:
    description: Utilizalo para hacerte invisible
    usage: /invisible